// ═══════════════════════════════════════════════════════════════
// TECHNICAL INDICATORS
// ═══════════════════════════════════════════════════════════════
export const I = {
    sma: (p, n) => p.length < n ? null : +(p.slice(-n).reduce((a, b) => a + b, 0) / n).toFixed(4),
    ema: (p, n) => { if (p.length < n) return null; const k = 2 / (n + 1); let e = p.slice(0, n).reduce((a, b) => a + b, 0) / n; for (let i = n; i < p.length; i++)e = p[i] * k + e * (1 - k); return +e.toFixed(4); },
    rsi: (p, n = 14) => { if (p.length < n + 1) return null; let g = 0, l = 0; for (let i = 1; i <= n; i++) { const d = p[i] - p[i - 1]; d > 0 ? g += d : l -= d; } let ag = g / n, al = l / n; for (let i = n + 1; i < p.length; i++) { const d = p[i] - p[i - 1]; ag = (ag * (n - 1) + Math.max(d, 0)) / n; al = (al * (n - 1) + Math.max(-d, 0)) / n; } return al === 0 ? 100 : +(100 - 100 / (1 + ag / al)).toFixed(2); },
    macd: (p) => { if (p.length < 26) return { macd: null, sig: null, hist: null }; const e12 = I.ema(p, 12), e26 = I.ema(p, 26); if (!e12 || !e26) return { macd: null, sig: null, hist: null }; const m = +(e12 - e26).toFixed(4), sig = +(m * 0.85 + m * 0.15).toFixed(4); return { macd: m, sig, hist: +(m - sig).toFixed(4) }; },
    bb: (p, n = 20) => { if (p.length < n) return null; const sl = p.slice(-n), avg = sl.reduce((a, b) => a + b, 0) / n, std = Math.sqrt(sl.reduce((a, b) => a + (b - avg) ** 2, 0) / n); return { upper: +(avg + 2 * std).toFixed(4), mid: +avg.toFixed(4), lower: +(avg - 2 * std).toFixed(4) }; },
    stoch: (h, l, c, k = 14) => { if (c.length < k) return { k: null }; const hh = Math.max(...h.slice(-k)), ll = Math.min(...l.slice(-k)); return { k: hh === ll ? 50 : +((c[c.length - 1] - ll) / (hh - ll) * 100).toFixed(2) }; },
    willr: (h, l, c, n = 14) => { if (c.length < n) return null; const hh = Math.max(...h.slice(-n)), ll = Math.min(...l.slice(-n)); return hh === ll ? -50 : +((hh - c[c.length - 1]) / (hh - ll) * -100).toFixed(2); },
    atr: (h, l, c, n = 14) => { if (c.length < n + 1) return null; const trs = []; for (let i = 1; i < c.length; i++)trs.push(Math.max(h[i] - l[i], Math.abs(h[i] - c[i - 1]), Math.abs(l[i] - c[i - 1]))); return +(trs.slice(-n).reduce((a, b) => a + b, 0) / n).toFixed(4); },
    obv: (c, v) => { if (c.length < 2) return { val: null, trend: null }; let o = 0, p5 = 0; for (let i = 1; i < c.length; i++) { c[i] > c[i - 1] ? o += v[i] : c[i] < c[i - 1] ? o -= v[i] : 0; if (i === c.length - 6) p5 = o; } return { val: o, trend: o > p5 ? "UP" : "DOWN" }; },
    cci: (h, l, c, n = 20) => { if (c.length < n) return null; const tp = c.map((_, i) => (h[i] + l[i] + c[i]) / 3), sl = tp.slice(-n), avg = sl.reduce((a, b) => a + b, 0) / n, md = sl.reduce((a, b) => a + Math.abs(b - avg), 0) / n; return md === 0 ? 0 : +((tp[tp.length - 1] - avg) / (0.015 * md)).toFixed(2); },
    roc: (p, n = 10) => { if (p.length < n + 1) return null; return +((p[p.length - 1] - p[p.length - 1 - n]) / p[p.length - 1 - n] * 100).toFixed(2); },
    cross: (p) => { if (p.length < 52) return "NONE"; const s50n = I.sma(p, 50), s50p = I.sma(p.slice(0, -1), Math.min(50, p.length - 1)), s200n = I.sma(p, Math.min(200, p.length)); if (!s50n) return "NONE"; if (s200n && s50n > s200n && s50p && s50p <= s200n) return "GOLDEN"; if (s200n && s50n < s200n && s50p && s50p >= s200n) return "DEATH"; if (s200n && s50n > s200n) return "ABOVE"; return "NONE"; },
    pivots: (h, l, c) => { if (!h?.length) return { s1: null, s2: null, r1: null, r2: null }; const hh = Math.max(...h.slice(-14)), ll = Math.min(...l.slice(-14)), pivot = (hh + ll + c[c.length - 1]) / 3; return { s1: +(2 * pivot - hh).toFixed(3), s2: +(pivot - (hh - ll)).toFixed(3), r1: +(2 * pivot - ll).toFixed(3), r2: +(pivot + (hh - ll)).toFixed(3) }; },
};
